### ISSUE TITLE
server-next depends on formidable and does not work on Cloudflare

### ISSUE THREAD

**Issue by valentinvieriu** [franciscop/server-next#1]
I really like the idea and simplicity of this project, but somehow I fail to use it in a CloudFlare Env. It seems that the dependency on formidable makes it quite hard to do this.
I don't understand how this be compatible with cloudflare, when the bundled index.js starts with
```
import formidable from 'formidable';
import http from 'http';
import zlib from 'zlib';
```

Can you support by explaining how should we build your project for Cloudflare?

**Comment by franciscop** [comment]
TBH, I don't remember 😬

So this experiment seemed to be a lot more complex than I initially thought so I didn't pursue it too deep. IIRC the idea was that you would install this and then locally run `rollup` with a configuration such as all dependencies are bundled. `formidable` is a dependency and will be installed locally when you install this, and then _your_ rollup would bundle formidable as well.

I think the reason I didn't bundle formidable fully was that I wasn't sure if I'd end up using that for parsing the requests with files or another library, so for now I left it at that.

In case it's not totally clear you should be using `server` instead for now for normal prod sites, but that is definitely not compatible with Cloudflare Workers, sorry about that.

**Comment by valentinvieriu** [comment]
:) Thank you for your response. I'm looking into this problem space, of compiling Nodejs ( javascript applications ) for Cloudflare workers, and indeed is complicated, as a lot of API are not available in V8 Isolates.
